name: ci

on:
  push:

jobs:
  docker:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          load: true
          #push: true
          tags: holos-docker:latest
